version: 2.1
orbs:
  python: circleci/python@2

jobs:
  test-python:
    docker:
      - image: cimg/python:3.12
    steps:
      - checkout
      - python/install-packages
      - run:
          name: Install dependencies
          command: pip install -r requirements.txt
      - run:
          name: Run flake8
          command: flake8 --exclude=venv* --statistics
      - run:
          name: Run tests with coverage and XML output
          command: pytest -v --cov=calculator --cov-report=xml --junitxml=junit.xml || ((($? == 5)) && echo 'Did not find any tests to run.')
      - store_test_results:
          path: junit.xml
      - store_artifacts:
          path: coverage.xml

  deploy:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: deploy
          command: '#e.g. ./deploy.sh'

workflows:
  build-and-test:
    jobs:
      - test-python
    # - deploy:
    #     requires:
    #       - test-python
